name: flutter_gstreamer_libs
description: "GStreamer library for Flutter"
version: 1.24.8
publish_to: none
homepage: https://github.com/ConferreAI/flutter_gstreamer_libs

environment:
  sdk: ^3.5.3
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: FlutterGstreamerLibsPlugin
      macos:
        pluginClass: FlutterGstreamerLibsPlugin

